# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.CustomerModel'),
        ),
    ]
