# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='engine_capacity',
            field=models.FloatField(),
        ),
    ]
