# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='date_resolved',
            field=models.DateField(null=True),
        ),
    ]
