# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0002_cities_contractor_countries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BodyTypes',
            new_name='BodyType',
        ),
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='EngineCapacities',
            new_name='EngineCapacity',
        ),
        migrations.RenameModel(
            old_name='EngineTypes',
            new_name='EngineType',
        ),
    ]
