# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0003_auto_20180129_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='responsible_contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.Contractor'),
        ),
    ]
