# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0003_auto_20171229_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
