# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0003_auto_20180102_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
                ('referencing_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.Offer')),
            ],
        ),
    ]
