# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 17:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0003_auto_20180131_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contractor', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='requesting_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_requests', to='web_client.Customer'),
        ),
        migrations.AlterField(
            model_name='inspectionrequest',
            name='responsible_contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_requests', to='web_client.Contractor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,12}$')]),
        ),
    ]
