# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0003_auto_20180122_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractorModel',
            new_name='Contractor',
        ),
    ]
