# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0004_auto_20180130_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
