# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0004_auto_20171226_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='engine_capacity',
            field=models.CharField(max_length=4),
        ),
    ]
