# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('currency_abbr', models.CharField(max_length=5)),
            ],
        ),
    ]
