# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0005_auto_20171226_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
    ]
