# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0005_auto_20180122_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('corresponding_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_client.Post')),
                ('requesting_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_customer', to=settings.AUTH_USER_MODEL)),
                ('responsible_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
